controller_list:
  - name: fake_left_arm_controller
    joints:
      - torso_yaw_joint
      - left_arm_shoulder_pitch_joint
      - left_arm_shoulder_roll_joint
      - left_arm_shoulder_yaw_joint
      - left_arm_elbow_roll_joint
      - left_arm_forearm_yaw_joint
      - left_arm_wrist_roll_joint
  - name: fake_right_arm_controller
    joints:
      - torso_yaw_joint
      - right_arm_shoulder_pitch_joint
      - right_arm_shoulder_roll_joint
      - right_arm_shoulder_yaw_joint
      - right_arm_elbow_roll_joint
      - right_arm_forearm_yaw_joint
      - right_arm_wrist_roll_joint
  - name: fake_head_controller
    joints:
      - torso_yaw_joint
      - head_yaw_joint
      - head_pitch_joint
  - name: fake_left_hand_controller
    joints:
      - left_gripper_joint
  - name: fake_right_hand_controller
    joints:
      - right_gripper_joint
  - name: fake_tray_controller
    joints:
      - torso_yaw_joint
      - tray_joint